config/routes.rb
Rails.application.routes.draw do

  root to: 'images#index'
  resources :images
  resources :users
  resources :about, only: :index

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'

end

app/models/image.rb
class Image < ActiveRecord::Base
  # has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :imgname, :category, :tag, :description, :imgurl, :thumb, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

 validates :username, presence: true, uniqueness: true
 has_secure_password

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def authenticate
    redirect_to new_user_path unless
    session[:current_user_id]
  end

  def current_user
    User.find(session[:current_user_id]) if
    session[:current_user_id]
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :authenticate, only: :new

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    @image.update(image_params)
    redirect_to @image
  end

  def show
    @image = Image.find(params[:id])
  end

  def create
    @image = Image.create(image_params)
    @image.save
    redirect_to @image
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to @image
  end

  private

  def image_params
    params.require(:image).permit(:imgname, :category, :tag, :description, :imgurl, :thumb)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id

      redirect_to new_image_path

    else
      redirect_to root_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to images_path

    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    session[:current_user_id] = nil
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="container">
<div class="about">
  <p><img src="<%= asset_path 'self-portrait.png' %>"   /></p>

  <h1>Hi!</h1>

  <p>I’m Jasmine, a front-end developer, graphic designer, and illustrator. I have experience working in art direction, branding, web design, event design, and illustration. My personal work explores the connection  between art, science, and techonology.</p>

  <p>Interested in collaborating, or just want to say hi? Feel free to reach me at  <strong>jasmine[at]jasminevollherbst.com</strong></p>

  <p>You can also find me here:</p>

  <p> <a href="http://www.linkedin.com/in/jasminevollherbst"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  	 width="32px" height="32px" viewBox="0 0 32 32" enable-background="new 0 0 32 32" xml:space="preserve">
  <path fill="#555555" d="M30.7,0H1.3C0.6,0,0,0.6,0,1.3v29.3C0,31.4,0.6,32,1.3,32h29.3c0.7,0,1.301-0.6,1.301-1.3V1.3
  	C32,0.6,31.4,0,30.7,0z M9.5,27.3H4.7V12h4.8V27.3z M7.1,9.9c-1.5,0-2.8-1.2-2.8-2.8c0-1.5,1.2-2.8,2.8-2.8c1.5,0,2.8,1.2,2.8,2.8
  	S8.6,9.9,7.1,9.9z M27.3,27.3h-4.7V19.9c0-1.801,0-4-2.5-4s-2.8,1.9-2.8,3.9V27.4h-4.7V12H17v2.1h0.1c0.601-1.2,2.2-2.5,4.5-2.5
  	c4.801,0,5.7,3.2,5.7,7.3V27.3z"/>
  </svg></a> &nbsp;
  <!-- Generator: Adobe Illustrator 16.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
  <a href="http://www.github.com/jvollherbst"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  	 width="32px" height="32px" viewBox="0 0 32 32" enable-background="new 0 0 32 32" xml:space="preserve">
  <path fill="#555555" d="M16,0.4c-8.8,0-16,7.2-16,16c0,7.1,4.6,13.1,10.9,15.2c0.8,0.101,1.1-0.3,1.1-0.8c0-0.399,0-1.399,0-2.7
  	c-4.5,1-5.4-2.1-5.4-2.1c-0.7-1.8-1.8-2.3-1.8-2.3c-1.5-1,0.1-1,0.1-1c1.6,0.1,2.5,1.6,2.5,1.6c1.4,2.4,3.7,1.7,4.7,1.3
  	c0.1-1,0.6-1.699,1-2.1c-3.6-0.4-7.3-1.8-7.3-7.9c0-1.7,0.6-3.2,1.6-4.3c-0.2-0.4-0.7-2,0.2-4.2c0,0,1.3-0.4,4.4,1.6
  	c1.3-0.4,2.6-0.5,4-0.5c1.4,0,2.7,0.2,4,0.5C23.1,6.6,24.4,7,24.4,7c0.899,2.2,0.3,3.8,0.199,4.2c1,1.1,1.601,2.5,1.601,4.3
  	c0,6.1-3.7,7.5-7.3,7.9c0.6,0.5,1.1,1.5,1.1,3c0,2.1,0,3.899,0,4.399c0,0.4,0.3,0.9,1.1,0.8C27.4,29.5,32,23.5,32,16.4
  	C32,7.6,24.8,0.4,16,0.4z"/>
  </svg></a> &nbsp;

  <a href="https://twitter.com/JVollherbst">
  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  	 width="32px" height="32px" viewBox="0 0 32 32" enable-background="new 0 0 32 32" xml:space="preserve">
  <path fill="#555555" d="M32,6.1c-1.2,0.5-2.4,0.9-3.8,1C29.6,6.3,30.6,5,31.1,3.5C29.8,4.3,28.4,4.8,26.9,5.1C25.7,3.8,24,3,22.2,3
  	c-3.601,0-6.6,2.9-6.6,6.6c0,0.5,0.1,1,0.2,1.5C10.3,10.8,5.5,8.2,2.2,4.2c-0.6,1-0.9,2.1-0.9,3.3c0,2.3,1.2,4.3,2.9,5.5
  	c-1.1,0-2.1-0.3-3-0.8v0.1c0,3.2,2.3,5.8,5.3,6.4c-0.6,0.1-1.1,0.2-1.7,0.2c-0.4,0-0.8,0-1.2-0.101C4.4,21.4,6.9,23.3,9.7,23.4
  	c-2.2,1.8-5.1,2.8-8.2,2.8c-0.5,0-1.1,0-1.6-0.101C2.9,27.9,6.4,29,10.1,29c12.1,0,18.7-10,18.7-18.7c0-0.3,0-0.6,0-0.8
  	C30,8.5,31.1,7.4,32,6.1z"/>
  </svg></a>
  </p>

</div>
</div>

app/views/images/edit.html.erb
<div class ="form">
  <h1>Create New Menu Items</h1>
    <%= form_for @image, html: { multipart: true } do |f| %>
    <%= f.label :imgname%><br>
    <%= f.text_field :imgname%><br>

    <%= f.label :category%><br>
    <%= f.text_field :category%><br>

    <%= f.label :tag%><br>
    <%= f.text_field :tag%><br>

    <%= f.label :description%><br>
    <%= f.text_field :description%><br>

    <%= f.label :imgurl%><br>
    <%= f.text_field :imgurl%><br>

    <%= f.label :thumb%><br>
    <%= f.text_field :thumb%><br>

    <br>
    <%= f.submit "Submit"%><br>
    <% end %>
</div>

app/views/images/index.html.erb
<div class="container">

  <h2 class="homepage">Jasmine Vollherbst is a developer and designer working at the intersection of art and technology. </h2>

</div>

<div id="thumbs">
<% @images.each do |i| %>
     <div class="thumbnail <%= i.category %>"><img src="<%= asset_path i.thumb %>" class="img-thumb" /></div>
 <% end %>
</div>

app/views/images/new.html.erb
<div class ="form">
  <h1>Create New Menu Items</h1>
    <%= form_for @image, html: { multipart: true } do |f| %>
    <%= f.label :imgname%><br>
    <%= f.text_field :imgname%><br>

    <%= f.label :category%><br>
    <%= f.text_field :category%><br>

    <%= f.label :tag%><br>
    <%= f.text_field :tag%><br>

    <%= f.label :description%><br>
    <%= f.text_area :description%><br>

    <%= f.label :imgurl%><br>
    <%= f.text_field :imgurl%><br>

    <%= f.label :thumb%><br>
    <%= f.text_field :thumb%><br>

    <br>
    <%= f.submit "Submit"%><br>
    <% end %>
</div>

app/views/images/show.html.erb
<div class="container">

    <div class="port-descr" id="descr">
     <h2><%= @image.imgname %></h2>
     <p><%= @image.description %></p>
    </div>

    <div class="port-img">
      <img src="<%= asset_path @image.imgurl %>" />
      <div class="edit">    
        <% if session[:current_user_id] %>
        <p><%= link_to 'Edit', edit_image_path(@image) %></p>
        <p><%= link_to 'Delete', image_path(@image), method: :delete %></p>
        <% end %>
      </div>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jasmine Vollherbst</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400|Roboto+Condensed" rel="stylesheet">
  <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">

  <script src="https://use.typekit.net/fet5jkl.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
<body>
<header>
  <h1 class="main-logo">jasmine[at]jasminevollherbst.com</h1>


  <nav>
    <ul>
      <li></li>
      <li> <a href="http://www.linkedin.com/in/jasminevollherbst"><i class="ion-social-linkedin-outline"></i></a></li>
      <li><a href="http://www.github.com/jvollherbst"><i class="ion-social-github-outline"></i></a></li>
      <li><a href="https://twitter.com/JVollherbst"><i class="ion-social-twitter-outline"></i>
      </a></li>
  </ul>
  </nav>
</header>

 <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<div class="container">
  <p>Login Here</p>
  <%= form_tag(sessions_path) do%>
  <%= label_tag :username %>
  <%= text_field_tag :username %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag "Login" %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="form">
<h1>Register to Create an Account</h1>
  <%= form_for @user do |f| %>

  <%= f.label :username%><br>
  <%= f.text_field :username%><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <br>
  <%= f.submit "Register"%><br>
  <% end %>
</div>